### PR TITLE
Added support for custom cache key provider

### PR DESCRIPTION
**Pull request by steuic**
InMemoryCacheHandler now supports custom cache key provider.

**Custom cache key provider and already implemented cache key providers**
Interface ```ICacheKeysProvider``` allow to implement custom cache key providers.
Provider ```DefaultCacheKeysProvider``` provides cache key by concatenation of http method (GET or HEAD) and uri.
Provider ```MethodUriHeadersCacheKeysProvider``` provides cache key by concatenation of http method (GET or HEAD), specific  http headers and uri.

**Backward compatibility**
When no custom cache key provider is specified, InMemoryCacheHandler will use ```DefaultCacheKeysProvider``` which resemble previous cache key composition strategy: concatenation of http method (GET or HEAD) and uri. This allow backward compatibility.

### CODE REVIEW

**Comment by thomasgalliker** [comment]
Nice idea. I gonna have a review asap.

**Comment by thomasgalliker** [comment]
@steuic I added some unit tests. Can you please have a look at the test ShouldGetKey_WithoutMatchingHeader. I think something is going wrong there. The current output key is `"MET_GET;HEA_;HEA_;URI_http://unittest/;"` which seams to be odd. Do we really have to include headers which are specified to be part of the key even if the request message does not contain them?

**Comment by thomasgalliker** [comment]
@steuic you can check the latest pre-release nuget. Your change should be part of it.

**Comment by steuic** [comment]
Thank you Thomas.
👍
________________________________

**Pull request merged**
